### ISSUE TITLE
Add those players to integration list as well

### ISSUE THREAD

**Issue by bebrites** [decred/dcrpayments#11]
There are some big players on the E-commerce sphere that aren't on the list:
- Volusion - https://www.volusion.com
- 3dCart - https://www.3dcart.com
- LemonStand - https://lemonstand.com 
- YoKart - http://www.yo-kart.com 
- Ultracart - https://www.ultracart.com 
- CommerceHub - https://www.commercehub.com 
- CoreCommerce - https://www.corecommerce.com 

It would be nice to add them to the Roadmap.
Thanks,
Bernardo Brites

**Comment by jolan** [comment]
I've updated the README with a more plausible list of integrations that are easy for us to support.  Unfortunately, none of the ones mentioned here are on the list.

I'm not going to add these to the roadmap since it is unlikely it will happen unless someone shows up to do the work in which case they can add it themselves to the roadmap with a pull request.
